# This file was generated by GoReleaser. DO NOT EDIT.
cask "dr-cli" do
  name "dr-cli"
  desc "DataRobot command-line interface."
  homepage "https://www.datarobot.com"
  version "0.2.32-beta.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dr"

  on_macos do
    on_intel do
      url "https://github.com/datarobot-oss/cli/releases/download/v#{version}/dr_v#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/datarobot-oss/cli/"
      sha256 "e38f57b3527764d95e7b491ed0acefddec5b6f6a8f778a4a865a42f9bf1cdcd9"
    end
    on_arm do
      url "https://github.com/datarobot-oss/cli/releases/download/v#{version}/dr_v#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/datarobot-oss/cli/"
      sha256 "aac26acce356980249541a3093ebd353f01adc0c8460d7057ad439c60dc808c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/datarobot-oss/cli/releases/download/v#{version}/dr_v#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/datarobot-oss/cli/"
      sha256 "bbec9b386b098432f22d46b0fe8ff505b276e76335d8e9a5e382a0b3832e9ee2"
    end
    on_arm do
      url "https://github.com/datarobot-oss/cli/releases/download/v#{version}/dr_v#{version}_Linux_arm64.tar.gz",
        verified: "github.com/datarobot-oss/cli/"
      sha256 "38b65c10be4008c943d96371887b071aa2d4a3b2a3fa707aa99f15e7952cc47f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dr"]
    end
  end

  # No zap stanza required
end
