# This file was generated by GoReleaser. DO NOT EDIT.
cask "dr-cli" do
  name "dr-cli"
  desc "DataRobot command-line interface."
  homepage "https://www.datarobot.com"
  version "0.2.19"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dr"

  on_macos do
    on_intel do
      url "https://github.com/datarobot-oss/cli/releases/download/v#{version}/dr_v#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/datarobot-oss/cli/"
      sha256 "88565d92aa93f93e0f253f5e05210f31196f677d6decf085bc31487b0ab378b0"
    end
    on_arm do
      url "https://github.com/datarobot-oss/cli/releases/download/v#{version}/dr_v#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/datarobot-oss/cli/"
      sha256 "997828961c014d3210974312a27a1ad69b250f4e46bb9042859d5e66fb0a4bc1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/datarobot-oss/cli/releases/download/v#{version}/dr_v#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/datarobot-oss/cli/"
      sha256 "abc329751a8ca244608670b2cfe7b37b47b5d950272c715a19fd89bd49ab9432"
    end
    on_arm do
      url "https://github.com/datarobot-oss/cli/releases/download/v#{version}/dr_v#{version}_Linux_arm64.tar.gz",
        verified: "github.com/datarobot-oss/cli/"
      sha256 "f40a6ddef2a91401fd56c2f7afd8708f287a3f23dca2a2e438943b87a2e331e8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dr"]
    end
  end

  # No zap stanza required
end
