# This file was generated by GoReleaser. DO NOT EDIT.
cask "dr-cli" do
  name "dr-cli"
  desc "DataRobot command-line interface."
  homepage "https://www.datarobot.com"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dr"

  on_macos do
    on_intel do
      url "https://github.com/datarobot-oss/cli/releases/download/v#{version}/dr_v#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/datarobot-oss/cli/"
      sha256 "5de0812794818fc3fc0f3c583d43ee5ce77335e390be94f373e2778f0d3076b9"
    end
    on_arm do
      url "https://github.com/datarobot-oss/cli/releases/download/v#{version}/dr_v#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/datarobot-oss/cli/"
      sha256 "9dea835c90df8c534039696edd42a8ba300dee697835303b0778a7140a7516a1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/datarobot-oss/cli/releases/download/v#{version}/dr_v#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/datarobot-oss/cli/"
      sha256 "30ef5c8bb2c3635a29d38d2a263c07f9ffa0c69f1f0e49dfa8dd3042b81ecc4d"
    end
    on_arm do
      url "https://github.com/datarobot-oss/cli/releases/download/v#{version}/dr_v#{version}_Linux_arm64.tar.gz",
        verified: "github.com/datarobot-oss/cli/"
      sha256 "90bd85c94cd4194f4577385f7846890e5c876b13edd023050c5751c891544cd1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dr"]
    end
  end

  # No zap stanza required
end
