# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dr < Formula
  desc "DataRobot command-line interface."
  homepage "https://github.com/datarobot-oss/cli"
  version "0.0.12"
  license "Apache-2.0"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datarobot-oss/cli/archive/refs/tags/v0.0.12.tar.gz", using: CurlDownloadStrategy
      sha256 "950d3bef620ee88cc44e6b305a7a0e71f49d3baf1bc448f764baa8938e66bd73"

      def install
        system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/datarobot/cli/internal/version.Version=v0.0.12 -X github.com/datarobot/cli/internal/version.GitCommit=54b95a7 -X github.com/datarobot/cli/internal/version.BuildDate=2025-10-02T21:06:44Z")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datarobot-oss/cli/archive/refs/tags/v0.0.12.tar.gz", using: CurlDownloadStrategy
      sha256 "9247c98329295f24e4f67e7b307a624e99ef08fce87f3d4ab78a1350ca1e43c5"

      def install
        system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/datarobot/cli/internal/version.Version=v0.0.12 -X github.com/datarobot/cli/internal/version.GitCommit=54b95a7 -X github.com/datarobot/cli/internal/version.BuildDate=2025-10-02T21:06:44Z")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/datarobot-oss/cli/archive/refs/tags/v0.0.12.tar.gz", using: CurlDownloadStrategy
      sha256 "f03e4865beb2b10bae969a98f3504c33953105570f97d6b65528be16da8623a0"
      def install
        system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/datarobot/cli/internal/version.Version=v0.0.12 -X github.com/datarobot/cli/internal/version.GitCommit=54b95a7 -X github.com/datarobot/cli/internal/version.BuildDate=2025-10-02T21:06:44Z")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/datarobot-oss/cli/archive/refs/tags/v0.0.12.tar.gz", using: CurlDownloadStrategy
      sha256 "f12e3e73bdfbcfc1d52f77f0ecfa5d9326004448491a9d6cad86ac5d23ce562d"
      def install
        system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/datarobot/cli/internal/version.Version=v0.0.12 -X github.com/datarobot/cli/internal/version.GitCommit=54b95a7 -X github.com/datarobot/cli/internal/version.BuildDate=2025-10-02T21:06:44Z")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datarobot-oss/cli/archive/refs/tags/v0.0.12.tar.gz", using: CurlDownloadStrategy
      sha256 "ba97b2315dc28e39a678103fa4d39596a9e729ea58ccaba6b79429571cade496"
      def install
        system "go", "build", *std_go_args(ldflags: "-s -w -X github.com/datarobot/cli/internal/version.Version=v0.0.12 -X github.com/datarobot/cli/internal/version.GitCommit=54b95a7 -X github.com/datarobot/cli/internal/version.BuildDate=2025-10-02T21:06:44Z")
      end
    end
  end

  head "https://github.com/datarobot-oss/cli.git", branch: "main"

  test do
    system bin/"dr", "version"
  end
end
