# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dr < Formula
  desc "DataRobot command-line interface."
  homepage "https://github.com/datarobot-oss/cli"
  version "0.0.8"
  license "Apache-2.0"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datarobot-oss/cli/releases/download/v0.0.8/dr_v0.0.8_Darwin_x86_64.tar.gz", using: GitDownloadStrategy
      sha256 "f15d1d32f2f756da5d75e308b216c6ae46a2f584c73eca5d666e4a241fe5b374"

      def install
        system "go", "build", "-ldflags", "-X github.com/datarobot/cli/internal/version.Version=v0.0.8 -X github.com/datarobot/cli/internal/version.GitCommit=862c430 -X github.com/datarobot/cli/internal/version.BuildDate=2025-10-02T20:28:39Z", "-o", bin/"dr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datarobot-oss/cli/releases/download/v0.0.8/dr_v0.0.8_Darwin_arm64.tar.gz", using: GitDownloadStrategy
      sha256 "fb0945c2efa7b401ce8e85b312b58a9d9513ac58c06baddd1d28d50f507e9d0a"

      def install
        system "go", "build", "-ldflags", "-X github.com/datarobot/cli/internal/version.Version=v0.0.8 -X github.com/datarobot/cli/internal/version.GitCommit=862c430 -X github.com/datarobot/cli/internal/version.BuildDate=2025-10-02T20:28:39Z", "-o", bin/"dr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/datarobot-oss/cli/releases/download/v0.0.8/dr_v0.0.8_Linux_x86_64.tar.gz", using: GitDownloadStrategy
      sha256 "473bab2c2116f13443f254fbdc6da11f306340ad57627b38e3cfbc200072fc0d"
      def install
        system "go", "build", "-ldflags", "-X github.com/datarobot/cli/internal/version.Version=v0.0.8 -X github.com/datarobot/cli/internal/version.GitCommit=862c430 -X github.com/datarobot/cli/internal/version.BuildDate=2025-10-02T20:28:39Z", "-o", bin/"dr"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/datarobot-oss/cli/releases/download/v0.0.8/dr_v0.0.8_Linux_armv6.tar.gz", using: GitDownloadStrategy
      sha256 "abde40259fc1e3c40649e7b1bed65425079272964c32981fbd97b0914d946ab1"
      def install
        system "go", "build", "-ldflags", "-X github.com/datarobot/cli/internal/version.Version=v0.0.8 -X github.com/datarobot/cli/internal/version.GitCommit=862c430 -X github.com/datarobot/cli/internal/version.BuildDate=2025-10-02T20:28:39Z", "-o", bin/"dr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datarobot-oss/cli/releases/download/v0.0.8/dr_v0.0.8_Linux_arm64.tar.gz", using: GitDownloadStrategy
      sha256 "7ce0da246c9b8b01f2e1b104f1c6415c882e5d2660d2eb9b310ab9b087d1f30e"
      def install
        system "go", "build", "-ldflags", "-X github.com/datarobot/cli/internal/version.Version=v0.0.8 -X github.com/datarobot/cli/internal/version.GitCommit=862c430 -X github.com/datarobot/cli/internal/version.BuildDate=2025-10-02T20:28:39Z", "-o", bin/"dr"
      end
    end
  end

  head "https://github.com/datarobot-oss/cli.git", branch: "main"

  test do
    system bin/"dr", "version"
  end
end
